name: Lesson Proposal Form
description: Use this form to propose adding or transferring a lesson to The Carpentries Incubator.
title: "[Proposal]: "
labels: ["proposal"]
assignees:
  - tobyhodges
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in developing and sharing lesson materials! 
        To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. 
        Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. 
        
        Questions? Please email team@carpentries.org.
  - type: input
    id: topic
    attributes:
      label: 1. Lesson Topic
      description: What is the topic of your lesson or lesson proposal?
      placeholder: ex. Introduction to sourdough baking
    validations:
      required: true
  - type: input
    id: lang
    attributes:
      label: 2. Lesson Language
      description: What is the (human) language of the lesson?
      placeholder: ex. Español, Deutsch, English
    validations:
      required: true
  - type: input
    id: draft
    attributes:
      label: 3. Draft materials
      description: |
        Do you already have a draft of your lesson? 
        You are welcome to share materials at any stage of development. 
        If you already have drafted materials, please include a link.
      placeholder: ex. https://github.com/yourname/intro-to-sourdough
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        If you answered "No" to part 2, you can skip to question 5. Thank you for your lesson idea!
  - type: checkboxes
    id: existing-terms
    attributes:
      label: 4. Requirements for existing materials
      description: 'For existing lesson materials, please answer the following questions.'
      options:
        - label: do your lesson materials conform to our [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view)?
        - label: are your materials already on GitHub and do they use The Carpentries [lesson template](https://github.com/carpentries/styles) or [The Carpentries Workbench](https://carpentries.github.io/workbench/)? (you can visit [the Workbench tutorial](https://carpentries.github.io/sandpaper-docs/) to learn more about how to use our lesson infrastructure).
  - type: checkboxes
    attributes:
      label: 5. New repository creation
      description: |
        If you don't have draft materials already or your materials don't meet both criteria in part 4, you will need to have an new repository created in The Carpentries Incubator.
        
        Please check the box below if this is the case, and our Curriculum Team will make a new repository for you.
      options: 
        - label: I need a new repository created
  - type: checkboxes
    attributes:
      label: 6. Transfer existing repository
      description: |
        If you have existing lesson materials that meet both criteria in part 4, your repository can be transferred to The Carpentries Incubator.
        
        If your lesson meets the criteria and you would like your repository transferred, please check the box below.
      options: 
        - label: my lesson meets both criteria in part 4 and I would like to transfer the repository to The Carpentries Incubator
  - type: textarea
    id: collaborators
    attributes:
      label: 7. Collaborators
      description: |
        If you checked one of the boxes in part 5 or part 6, please list the GitHub handles for people who should have [Maintain access](https://help.github.com/en/articles/repository-permission-levels-for-an-organization) to your lesson. 
        If you don't know how to answer this question, don't worry! We can always add collaborators later.
      placeholder: ex. @MCMaurer @tobyhodges
  - type: textarea
    id: questions
    attributes:
      label: 8. Info/Questions
      description: |
        Is there any other information you would like us to have, or any other questions you have for us?
      placeholder: Feel free to share!
  - type: markdown
    attributes:
      value: |
        Thank you for sharing your lesson with The Carpentries Community!
      
